temas = {
    'clima': ['céu', 'frio', 'quente', 'chuva', 'sol', 'nublado', 'vento', 'tempestade', 'clima', 'neve',
              'calor', 'umidade', 'brisa', 'trovão', 'inverno', 'verão', 'nuvem', 'gelo', 'meteorologia',
              'rajada', 'outono', 'primavera', 'garoa', 'geada', 'temporal', 'brilho', 'nebulosidade',
              'arco-íris', 'tempestuoso', 'caloroso', 'fresco', 'seco', 'nebuloso', 'nevasca', 'céu limpo',
              'ventania', 'solstício', 'meteorológico', 'agrícola', 'índice pluviométrico', 'previsão',
              'climático', 'clima temperado', 'correnteza', 'clima seco', 'nuvens carregadas',
              'mudança climática'],

    'emoção': ['feliz', 'triste', 'animado', 'deprimido', 'contente', 'ansioso', 'nervoso', 'alegre',
               'chateado', 'emocionado', 'irritado', 'calmo', 'alegria', 'depressão', 'euforia',
               'tranquilidade', 'saudade', 'medo', 'raiva', 'ternura', 'melancolia', 'angústia',
               'aflição', 'empolgação', 'surpresa', 'felicidade', 'desânimo', 'entusiasmo', 'esperança',
               'gratidão', 'desespero', 'desgosto', 'satisfação', 'frustração', 'excitação', 'descontentamento',
               'paz', 'desalento', 'êxtase', 'desesperança', 'tédio', 'orgulho', 'vergonha', 'remorso',
               'compaixão', 'amor', 'luto', 'alegria'],

    'saúde': ['saúde', 'doença', 'hospital', 'médico', 'remédio', 'tratamento', 'sintoma', 'diagnóstico',
              'cura', 'vacina', 'enfermidade', 'cirurgia', 'enfermaria', 'paciente', 'emergência', 'consultório',
              'medicamento', 'nutrição', 'epidemia', 'pandemia', 'imunidade', 'contagioso', 'fisioterapia',
              'psicoterapia', 'hematologia', 'oncologia', 'terapia intensiva', 'enfermeiro', 'cardiologia',
              'neurologia', 'radiologia', 'oftalmologia', 'anestesia', 'reabilitação', 'diagnóstico precoce',
              'prevenção', 'tratamento experimental', 'sintoma crônico', 'mortalidade infantil', 'saúde mental',
              'saúde pública', 'doença crônica', 'genética', 'bem-estar', 'qualidade de vida', 'vírus',
              'bactéria', 'doenças infecciosas', 'endocrinologia'],

    'alimentação': ['comida', 'bebida', 'restaurante', 'jantar', 'almoço', 'café', 'refeição', 'cozinha',
                    'cardápio', 'prato', 'receita', 'gourmet', 'sabor', 'gastronomia', 'culinária', 'chef',
                    'padaria', 'sobremesa', 'hambúrguer', 'pizza', 'vegetariano', 'vegano', 'dieta',
                    'nutriente', 'vitamina', 'proteína', 'carboidrato', 'fibra', 'alimento', 'lanche',
                    'fast food', 'cozinhar', 'gastronômico', 'salada', 'fruta', 'legume', 'frutos do mar',
                    'carnes', 'sushi', 'sashimi', 'vinho', 'cerveja', 'suco', 'chá', 'água', 'refrigerante',
                    'padaria', 'doces', 'salgado'],

    'trabalho': ['trabalho', 'emprego', 'profissão', 'carreira', 'salário', 'empresa', 'negócio', 'ocupação',
                 'vaga', 'entrevista', 'reunião', 'projeto', 'trabalhar', 'colaborador', 'gestão', 'liderança',
                 'inovação', 'produtividade', 'mercado de trabalho', 'benefício', 'competência', 'qualificação',
                 'promoção', 'demissão', 'contrato', 'autônomo', 'freelancer', 'horário', 'equipe', 'trabalho remoto',
                 'escritório', 'home office', 'teletrabalho', 'trabalho em equipe', 'plano de carreira', 'estágio',
                 'aprendizado', 'eficiência', 'empregabilidade', 'sindicato', 'condições de trabalho', 'segurança no trabalho',
                 'estresse', 'realização profissional', 'motivação', 'crescimento profissional', 'oportunidade',
                 'trabalho temporário', 'jornada de trabalho', 'clima organizacional'],

    'educação': ['educação', 'escola', 'universidade', 'aula', 'professor', 'aluno', 'curso', 'matéria', 'ensino',
                 'aprendizado', 'licença', 'pesquisa', 'biblioteca', 'conhecimento', 'graduação', 'pós-graduação',
                 'mestrado', 'doutorado', 'disciplina', 'faculdade', 'estudo', 'pedagogia', 'capacitação',
                 'capacidade', 'competência', 'habilidade', 'didática', 'prova', 'avaliação', 'aprendizagem',
                 'currículo', 'metodologia', 'técnica', 'tecnologia educacional', 'inovação pedagógica', 'ensino à distância',
                 'EAD', 'professorado', 'educador', 'aprendizado contínuo', 'formação profissional', 'alfabetização',
                 'disciplina escolar', 'acesso à educação', 'educação inclusiva', 'ensino integral', 'educação infantil',
                 'educação básica', 'educação especial'],

    'tecnologia': ['tecnologia', 'computador', 'internet', 'software', 'hardware', 'programação', 'aplicativo',
                   'rede', 'sistema', 'dispositivo', 'inovação', 'inteligência artificial', 'tecnológico',
                   'tecnologia da informação', 'TI', 'código', 'desenvolvimento', 'web', 'mobile', 'cloud computing',
                   'integração', 'robótica', 'automação', 'machine learning', 'big data', 'analytics', 'segurança da informação',
                   'blockchain', 'criptomoeda', 'realidade virtual', 'realidade aumentada', 'gamificação', 'tecnologia emergente',
                   'indústria 4.0', 'transformação digital', 'futuro da tecnologia', 'engenharia de software', 'startup',
                   'empreendedorismo digital', 'inovação tecnológica', 'cibersegurança', 'desenvolvedor', 'tecnologia móvel',
                   'internet das coisas', 'IoT', 'dispositivo conectado', 'inteligência de dados', 'interface usuário',
                   'usabilidade'],

    'viagem': ['viagem', 'turismo', 'destino', 'hotel', 'voo', 'passagem', 'férias', 'passeio', 'excursão', 'bagagem',
               'avião', 'reserva', 'rota', 'roteiro', 'guia', 'viajante', 'mochila', 'check-in', 'check-out', 'aeroporto',
               'seguro viagem', 'turista', 'experiência', 'cultura local', 'destino internacional', 'ponto turístico',
               'hospedagem', 'hostel', 'albergue', 'pousada', 'recepção', 'viagem de negócios', 'viagem em família',
               'viagem solo', 'turismo rural', 'aventura', 'exploração', 'mala', 'companhia aérea', 'bagagem de mão',
               'traslado', 'câmbio', 'viagem econômica', 'viagem luxuosa', 'transporte público', 'táxi', 'ônibus turístico',
               'aluguel de carro', 'mapa', 'GPS'],

    'esporte': ['esporte', 'futebol', 'basquete', 'corrida', 'academia', 'treino', 'competição', 'time', 'jogo',
                'campeonato', 'maratona', 'torneio', 'ginásio', 'atleta', 'modalidade', 'vitória', 'derrota',
                'pódio', 'medalha', 'recorde', 'esportivo', 'campo', 'quadra', 'pista', 'natação', 'ciclismo',
                'ginástica', 'luta', 'voleibol', 'handebol', 'tênis', 'golfe', 'hóquei', 'surfe', 'skate',
                'snowboard', 'esqui', 'parapente', 'montanhismo', 'escalada', 'rapel', 'rafting', 'mergulho',
                'pesca esportiva', 'jet ski', 'windsurf', 'paraquedismo', 'bungee jump', 'corrida de rua', 'ultramaratona'],

    'cultura': ['cultura', 'música', 'arte', 'cinema', 'teatro', 'literatura', 'dança', 'exposição', 'livro',
                'filme', 'show', 'concerto', 'escultura', 'pintura', 'orquestra', 'comédia', 'drama', 'ação',
                'ficção', 'biografia', 'romance', 'poesia', 'ensaio', 'novela', 'conto', 'crônica', 'autor',
                'diretor', 'roteirista', 'coreógrafo', 'curador', 'público', 'espectador', 'plateia', 'bilheteria',
                'entrada', 'palco', 'cenário', 'figurino', 'iluminação', 'trilha sonora', 'tema', 'gênero', 'clássico',
                'contemporâneo', 'vanguarda', 'museu', 'galeria', 'exibição', 'performance', 'cultural'],

    'política': ['política', 'governo', 'eleição', 'partido', 'presidente', 'congresso', 'senado', 'voto',
                 'democracia', 'legislação', 'debate', 'campanha', 'oposição', 'situação', 'governador', 'prefeito',
                 'vereador', 'deputado', 'ministro', 'parlamento', 'corrupção', 'impeachment', 'golpe', 'protesto',
                 'manifestação', 'direitos', 'liberdade', 'justiça', 'constituição', 'político', 'cidadania', 'participação',
                 'reforma', 'poder', 'autoridade', 'gabinete', 'legislativo', 'executivo', 'judiciário', 'mandato', 'cargo',
                 'administração', 'administração pública', 'política externa', 'relações internacionais', 'diplomacia',
                 'tratado', 'acordo', 'negociação'],

    'economia': ['economia', 'mercado', 'dinheiro', 'banco', 'finança', 'investimento', 'ação', 'crédito',
                 'juros', 'inflação', 'PIB', 'comércio', 'câmbio', 'bolsa de valores', 'corretora', 'investidor',
                 'capital', 'rentabilidade', 'renda', 'riqueza', 'poupança', 'consumo', 'produção', 'indústria',
                 'agricultura', 'exportação', 'importação', 'empresário', 'desemprego', 'mercado de trabalho',
                 'inovação econômica', 'crescimento econômico', 'crise financeira', 'mercado financeiro',
                 'globalização', 'economia digital', 'economia colaborativa', 'economia criativa', 'economia solidária',
                 'sustentabilidade econômica', 'planejamento econômico', 'política econômica', 'indicadores econômicos',
                 'orçamento público', 'dívida pública', 'mercado cambial', 'consumidor', 'inadimplência',
                 'orçamento familiar', 'política fiscal', 'política monetária', 'economia emergente'],

    'natureza': ['natureza', 'floresta', 'animais', 'ecossistema', 'planta', 'biodiversidade', 'ambiente',
                 'sustentabilidade', 'conservação', 'paisagem', 'montanha', 'rio', 'oceano', 'deserto', 'selva',
                 'bioma', 'espécie', 'extinção', 'preservação', 'recursos naturais', 'clima', 'terra', 'água',
                 'ar', 'sol', 'lua', 'estrela', 'planeta', 'ecologia', 'geologia', 'meteorologia', 'meteorito',
                 'furacão', 'tornado', 'terremoto', 'vulcão', 'geografia', 'conchas', 'minerais', 'rochas', 'fóssil',
                 'reserva natural', 'parque nacional', 'área protegida', 'proteção ambiental', 'desenvolvimento sustentável',
                 'reciclagem', 'poluição', 'aquecimento global', 'sistema climático'],

    'ciência': ['ciência', 'pesquisa', 'experimento', 'laboratório', 'teoria', 'hipótese', 'físico', 'químico',
                'biólogo', 'astronomia', 'descoberta', 'microscópio', 'telescópio', 'genética', 'evolução', 'matéria',
                'energia', 'átomo', 'molécula', 'reação', 'catalisador', 'química', 'física', 'astronomia', 'biologia',
                'ecologia', 'ambiente', 'sustentabilidade', 'geologia', 'meteorologia', 'climatologia', 'oceanografia',
                'antropologia', 'arqueologia', 'paleontologia', 'entomologia', 'zoologia', 'botânica', 'microbiologia',
                'neurociência', 'psicologia', 'ciências sociais', 'ciências exatas', 'ciências humanas', 'ciências naturais',
                'método científico', 'tecnologia', 'inovação', 'ciência aplicada', 'pesquisa científica', 'academia'],

    'entretenimento': ['entretenimento', 'jogo', 'videogame', 'filme', 'série', 'televisão', 'música', 'show',
                       'celebridade', 'fama', 'festival', 'evento', 'parque', 'atração', 'recreação', 'diversão',
                       'passatempo', 'lazer', 'cultura pop', 'população', 'audiência', 'público', 'assistir', 'jogar',
                       'participar', 'entreter', 'espetáculo', 'performance', 'palco', 'pista', 'platéia', 'competição',
                       'esportivo', 'gameplay', 'streaming', 'lançamento', 'bilheteria', 'sucesso', 'flop', 'franquia',
                       'personagem', 'herói', 'vilão', 'ação', 'aventura', 'comédia', 'drama', 'ficção científica',
                       'fantasia', 'horror', 'suspense', 'romance', 'thriller'],

    'história': ['história', 'evento', 'passado', 'civilização', 'antiguidade', 'era', 'século', 'década',
                 'revolução', 'guerra', 'império', 'monarquia', 'república', 'ditadura', 'colonização', 'independência',
                 'descobrimento', 'descoberta', 'exploração', 'conquista', 'explorador', 'colonizador', 'rebelião',
                 'conflito', 'tratado', 'pacto', 'aliança', 'trégua', 'armistício', 'fronteira', 'território', 'nação',
                 'estado', 'governo', 'líder', 'ditador', 'monarca', 'presidente', 'imperador', 'rei', 'rainha', 'príncipe',
                 'princesa', 'guerreiro', 'soldado', 'exército', 'batalha', 'conquista', 'revolta', 'revolução', 'movimento'],

    'religião': ['religião', 'crença', 'fé', 'divindade', 'deus', 'deusa', 'espírito', 'alma', 'morte',
                 'vida', 'reencarnação', 'pecado', 'virtude', 'moral', 'ética', 'culto', 'ritual', 'sacerdote',
                 'monge', 'freira', 'igreja', 'templo', 'mesquita', 'sinagoga', 'catedral', 'capela', 'oração',
                 'meditação', 'jejum', 'caridade', 'peregrinação', 'sagrado', 'profano', 'santo', 'pecador',
                 'religioso', 'espiritual', 'buda', 'cristo', 'maomé', 'deusa', 'mitologia', 'teologia', 'salvação',
                 'iluminação', 'revelação', 'dogma', 'doutrina', 'escatologia', 'paraíso', 'inferno', 'divindade'],

    'social': ['social', 'sociedade', 'comunidade', 'coletivo', 'grupo', 'indivíduo', 'pessoa', 'cidadão',
               'civilização', 'cultura', 'etnia', 'raça', 'gênero', 'idade', 'geração', 'juventude', 'adolescência',
               'adulto', 'idoso', 'infância', 'família', 'amizade', 'amor', 'relacionamento', 'casamento', 'divórcio',
               'solteiro', 'solteira', 'namoro', 'união', 'conflito', 'harmonia', 'convivência', 'vizinho', 'colega',
               'amigo', 'amiga', 'parente', 'irmão', 'irmã', 'pai', 'mãe', 'filho', 'filha', 'parentesco', 'relação',
               'interação', 'inclusão', 'exclusão', 'preconceito', 'discriminação', 'igualdade', 'equidade', 'justiça'],

    'teatro': ['teatro', 'palco', 'espetáculo', 'ato', 'cena', 'drama', 'comédia', 'tragédia', 'musical',
               'encenação', 'direção', 'roteiro', 'ensaio', 'ensaiar', 'ensaiando', 'ensaios', 'ator', 'atriz',
               'personagem', 'papel', 'interpretação', 'performance', 'teatral', 'teatros', 'teatrais', 'trabalho',
               'produção', 'cênica', 'cenário', 'luz', 'figurino', 'maquiagem', 'encenar', 'encenações', 'espetáculos',
               'comédias', 'musicais', 'dramas', 'encena', 'dramático', 'encene', 'dramáticos', 'comédia', 'trágica',
               'peça', 'obras', 'pintura', 'filmes', 'gêneros'],

    'musica': ['música', 'nota', 'ritmo', 'melodia', 'harmonia', 'instrumento', 'guitarra', 'bateria',
               'piano', 'violino', 'flauta', 'saxofone', 'trompete', 'tuba', 'clarinete', 'orquestra', 'banda',
               'vocal', 'canto', 'cantar', 'cantando', 'cantores', 'cantoras', 'gênero', 'rap', 'hip hop', 'pop',
               'rock', 'metal', 'blues', 'jazz', 'clássica', 'folclore', 'sertaneja', 'sertanejo', 'funk', 'country',
               'dance', 'eletrônica', 'alternativa', 'indie', 'punk', 'reggae', 'músico', 'músicos', 'público',
               'gêneros', 'oportunidade', 'palco', 'espetáculo'],

    'tempo': ['tempo', 'relógio', 'hora', 'minuto', 'segundo', 'dia', 'semana', 'mês', 'ano', 'estação',
              'primavera', 'verão', 'outono', 'inverno', 'calendário', 'feriado', 'hora certa', 'período', 'cronograma',
              'horário', 'cronometrar', 'cronometrando', 'temporada', 'cronometrados', 'cronometram', 'calendários',
              'feriados', 'períodos', 'minutos', 'férias', 'semana', 'cada', 'fim', 'ontem', 'perto', 'além', 'anteriormente',
              'amanhã', 'sexta', 'sábado', 'domingo', 'amanhecer', 'madrugada', 'noturno', 'semanas', 'longe', 'finais',
              'ainda', 'muito', 'parecido', 'verdade', 'até'],

    'internet': ['internet', 'web', 'navegador', 'pesquisa', 'site', 'página', 'web site', 'on-line', 'web sites',
                 'rede', 'reduzir', 'mais', 'computadores', 'conectados', 'limites', 'época', 'web redes', 'usos',
                 'verdade', 'mais', 'tudo', 'outros', 'mais', 'ainda', 'muito', 'mais', 'mais', 'outros', 'nada',
                 'verdade', 'uma', 'gente', 'algumas', 'trabalho', 'tudo', 'outros', 'muito', 'até', 'onde', 'certa',
                 'um', 'alguns', 'pouco', 'um', 'fato', 'meio', 'até', 'nós'],

    'dados': ['dados', 'informação', 'informação', 'recolher', 'recolhendo', 'informação', 'computadores', 'informação',
              'tempos', 'dia', 'computadores', 'informação', 'computadores', 'estes', 'computadores', 'base', 'qualquer',
              'outros', 'outros', 'outros', 'outros', 'nada', 'sistema', 'outros', 'muito', 'outros', 'apenas', 'qualquer',
              'mais', 'web sites', 'pouco', 'outros', 'muito', 'outros', 'informação', 'outros', 'mais', 'não', 'mais',
              'outros', 'apenas', 'outros', 'toda', 'muito', 'completamente', 'não', 'toda', 'mais', 'nada', 'certa',
              'informação', 'usos', 'recolher', 'ainda'],

    'segurança': ['segurança', 'câmera', 'segurança', 'segurança', 'segurança', 'causas', 'muitos', 'segurança',
                  'segurança', 'fato', 'câmeras', 'aumentar', 'redes', 'outros', 'dados', 'sistema', 'informação',
                  'computadores', 'outros', 'outros', 'mais', 'ainda', 'alguns', 'nada', 'fato', 'segurança',
                  'outros', 'outros', 'ainda', 'ainda', 'qualquer', 'alguns', 'muito', 'nada', 'segurança',
                  'segurança', 'muito', 'verdade', 'informação', 'outros', 'dados', 'informação', 'qualquer',
                  'outros', 'usos', 'até', 'mais', 'uma', 'outros', 'até', 'outros', 'certa', 'segurança'],

    'energia': ['energia', 'elétrica', 'combustível', 'energia', 'solar', 'energia', 'energia', 'energia',
                'energia', 'elétrica', 'geração', 'energia', 'solar', 'energia', 'energia', 'energia', 'geração',
                'elétrica', 'energia', 'sistema', 'sistema', 'energia', 'energia', 'energia', 'elétrica', 'energia',
                'elétrica', 'energia', 'energia', 'energia', 'energia', 'energia', 'energia', 'energia', 'energia',
                'energia', 'elétrica', 'energia', 'sistema', 'energia', 'energia', 'energia', 'energia', 'energia',
                'energia', 'energia', 'energia', 'energia', 'energia', 'energia', 'energia', 'energia', 'energia',
                'elétrica', 'energia'],

    'conhecimento': ['conhecimento', 'científico', 'informação', 'tecnologia', 'científica', 'informação',
                     'aprendizado', 'aprendendo', 'recolhendo', 'informação', 'outros', 'muitos', 'outros',
                     'segurança', 'sistema', 'outros', 'segurança', 'sistema', 'segurança', 'segurança', 'informação',
                     'segurança', 'sistemas', 'outros', 'sistema', 'pouco', 'outros', 'outros', 'outros', 'nada',
                     'informação', 'informação', 'informação', 'informação', 'internet', 'computadores', 'sistema',
                     'outros', 'usos', 'sistema', 'outros', 'sistema', 'sistema', 'sistema', 'sistema', 'outros',
                     'sistema', 'outros', 'sistema', 'segurança', 'muito', 'outros'],

    'saúde': ['saúde', 'medicina', 'hospital', 'enfermagem', 'paciente', 'médico', 'enfermeiro', 'cirurgião',
              'consultório', 'sintoma', 'tratamento', 'remédio', 'medicamento', 'farmácia', 'diagnóstico', 'doença',
              'vírus', 'bactéria', 'contágio', 'epidemia', 'pandemia', 'vacina', 'imunização', 'prevenção', 'cura',
              'saúde mental', 'psicologia', 'psiquiatria', 'bem-estar', 'nutrição', 'exercício físico', 'vida saudável',
              'qualidade de vida', 'higiene', 'alimentação', 'obesidade', 'sedentarismo', 'tabagismo', 'álcool', 'drogas',
              'acidente', 'emergência', 'primeiros socorros', 'ambulância', 'seguro saúde', 'sistema de saúde', 'medicina preventiva',
              'medicina curativa', 'medicina de emergência', 'tratamento médico', 'consultas médicas', 'check-up médico'],

    'educação': ['educação', 'escola', 'ensino', 'aprendizado', 'professor', 'aluno', 'sala de aula', 'educação',
                 'básica', 'ensino médio', 'ensino fundamental', 'ensino superior', 'universidade', 'faculdade',
                 'instituto', 'escola técnica', 'currículo', 'matéria', 'disciplina', 'prova', 'nota', 'aprendizagem',
                 'conhecimento', 'habilidade', 'competência', 'pedagogia', 'didática', 'educação infantil', 'pedagogo',
                 'diretor', 'coordenador', 'grade curricular', 'apostila', 'livro didático', 'biblioteca', 'leitura',
                 'escrita', 'aritmética', 'geometria', 'história', 'ciências', 'biologia', 'física', 'química', 'matemática',
                 'língua portuguesa', 'língua estrangeira', 'inglês', 'espanhol', 'francês', 'arte', 'música', 'educação física'],

    'trabalho': ['trabalho', 'emprego', 'profissão', 'carreira', 'trabalhador', 'empregado', 'empregador', 'chefe',
                 'colaborador', 'funcionário', 'empresa', 'negócio', 'escritório', 'indústria', 'comércio', 'serviço',
                 'produção', 'trabalho remoto', 'teletrabalho', 'freelancer', 'autônomo', 'chefia', 'liderança', 'equipe',
                 'colega', 'colega de trabalho', 'ambiente de trabalho', 'contrato', 'salário', 'remuneração', 'benefício',
                 'promoção', 'demissão', 'desemprego', 'mercado de trabalho', 'entrevista', 'currículo', 'habilidade',
                 'competência', 'qualificação', 'treinamento', 'capacitação', 'oportunidade', 'economia', 'mercado', 'setor',
                 'empresarial', 'globalização', 'inovação', 'empreendedorismo', 'start-up', 'gestão', 'administração'],

    'moda': ['moda', 'roupa', 'estilo', 'desfile', 'tendência', 'designer', 'modelo', 'acessório', 'beleza', 'maquiagem', 'cabelo', 'cosmético',
             'passarela', 'estilista', 'elegância', 'moda urbana', 'fashion week', 'coleção', 'tecido', 'costura', 'alta costura',
             'moda masculina', 'moda feminina', 'glamour', 'tendências de verão', 'tendências de inverno', 'tendências de primavera',
             'estilo casual', 'estilo formal', 'vestuário', 'combinação de cores', 'estampa', 'acessórios de moda', 'pulseira', 'colar',
             'sapatos', 'bolsa', 'desenhista de moda', 'beleza natural', 'cosméticos orgânicos', 'penteado', 'desfile de moda', 'look do dia',
             'ícone de moda', 'moda vintage', 'moda contemporânea', 'alfaiate', 'estilização', 'tendências globais', 'influência da moda'],

     'filosofia': ['filosofia', 'pensamento', 'ética', 'moral', 'existência', 'sabedoria', 'conhecimento', 'reflexão', 'sociedade', 'indivíduo',
                  'teoria', 'crença', 'filósofo', 'lógica', 'metafísica', 'epistemologia', 'humanismo', 'racionalidade', 'dialética',
                  'ética aplicada', 'filosofia política', 'filosofia da mente', 'livre-arbítrio', 'moralidade', 'virtude', 'justiça', 'verdade',
                  'paradoxo', 'pensador', 'escola filosófica', 'fenomenologia', 'existencialismo', 'pragmatismo', 'empirismo', 'racionalismo',
                  'ontologia', 'estética', 'filosofia oriental', 'ética profissional', 'moralidade pública', 'filosofia da ciência', 'ética ambiental',
                  'ética empresarial', 'filosofia moral', 'epifania', 'pensamento crítico', 'ideologia', 'conceito', 'argumentação'],

    'literatura': ['literatura', 'livro', 'autor', 'poesia', 'romance', 'conto', 'escritor', 'leitura', 'biblioteca', 'narrativa', 'editor', 'obra',
                   'prosa', 'verso', 'crítica literária', 'ficção', 'não ficção', 'literatura clássica', 'literatura contemporânea', 'best-seller',
                   'personagem', 'enredo', 'narrador', 'estilo literário', 'crônica', 'literatura infantil', 'literatura juvenil', 'literatura brasileira',
                   'literatura estrangeira', 'literatura mundial', 'poeta', 'romance histórico', 'literatura de ficção científica', 'literatura fantástica',
                   'drama literário', 'sátira', 'ensaio', 'obra-prima', 'biografia', 'autobiografia', 'trama', 'escrita criativa', 'literatura de não ficção',
                   'literatura de mistério', 'literatura gótica', 'literatura erótica', 'literatura de viagem', 'literatura experimental'],

    'meio_ambiente': ['meio ambiente', 'sustentabilidade', 'reciclagem', 'conservação', 'poluição', 'ecologia', 'energia renovável', 'desmatamento',
                      'biodiversidade', 'clima', 'recursos naturais', 'ambientalista', 'preservação', 'aquecimento global', 'impacto ambiental',
                      'carbono neutro', 'desenvolvimento sustentável', 'floresta', 'oceanos', 'extinção', 'ecossistema', 'biodegradável',
                      'poluição do ar', 'poluição da água', 'política ambiental', 'consciência ambiental', 'ecoturismo', 'aquecimento global',
                      'crise climática', 'energia limpa', 'política de sustentabilidade', 'recursos hídricos', 'ecossistemas marinhos', 'resíduos sólidos',
                      'contaminação', 'espécies ameaçadas', 'proteção ambiental', 'conservação da natureza', 'reflorestamento', 'impacto ecológico',
                      'biologia da conservação', 'gestão ambiental', 'tecnologias verdes', 'política de conservação', 'sustentabilidade urbana', 'consumo consciente',
                      'bem-estar animal', 'crise ambiental', 'futuro sustentável'],

    'gastronomia': ['gastronomia', 'culinária', 'prato', 'refeição', 'chef', 'restaurante', 'cozinha', 'receita', 'ingrediente', 'menu', 'gourmet', 'especialidade',
                    'cozinha internacional', 'cozinha regional', 'cozinha brasileira', 'cozinha italiana', 'cozinha francesa', 'cozinha asiática', 'cozinha mediterrânea',
                    'cozinha vegetariana', 'cozinha vegana', 'cozinha saudável', 'cozinha rápida', 'cozinha gourmet', 'culinária contemporânea', 'culinária tradicional',
                    'gastronomia molecular', 'vinho', 'harmonização', 'sobremesa', 'entrada', 'prato principal', 'aperitivo', 'bebida', 'coquetel', 'cerveja artesanal',
                    'vinho tinto', 'vinho branco', 'vinho rosé', 'espumante', 'cozinha do chef', 'culinária experimental', 'gastronomia étnica', 'cozinha de fusão',
                    'cozinha de autor', 'cozinha de rua', 'padaria', 'confeitaria', 'churrasco', 'culinária caseira', 'culinária rápida'],

    'finanças': ['finanças', 'dinheiro', 'investimento', 'banco', 'crédito', 'juros', 'orçamento', 'economia', 'ação', 'mercado', 'capital', 'renda',
                 'finanças pessoais', 'finanças corporativas', 'mercado financeiro', 'planejamento financeiro', 'estratégia de investimento', 'bolsa de valores',
                 'corretora de valores', 'gestão financeira', 'fundo de investimento', 'ativos financeiros', 'passivos financeiros', 'risco financeiro', 'retorno financeiro',
                 'análise financeira', 'fluxo de caixa', 'orçamento familiar', 'planejamento tributário', 'mercado de capitais', 'economia global', 'taxa de câmbio',
                 'crise financeira', 'inflação', 'deflação', 'indicadores econômicos', 'estratégia empresarial', 'finanças públicas', 'política monetária',
                 'política fiscal', 'bancarrota', 'falência', 'investidor', 'fundos mútuos', 'empréstimo', 'financiamento', 'consultoria financeira', 'planejador financeiro',
                 'seguro de vida', 'previdência privada', 'impostos', 'contabilidade financeira'],

     'automobilismo': ['automobilismo', 'carro', 'corrida', 'moto', 'pista', 'automóvel', 'veículo', 'motor', 'volante', 'fórmula 1', 'piloto', 'competição',
                      'automobilismo esportivo', 'automobilismo clássico', 'automobilismo moderno', 'automobilismo de luxo', 'automobilismo urbano', 'automobilismo rural',
                      'automobilismo de velocidade', 'automobilismo off-road', 'automobilismo de rally', 'automobilismo de endurance', 'automobilismo de circuito',
                      'automobilismo de pista', 'automobilismo de rua', 'automobilismo de autódromo', 'automobilismo de teste', 'automobilismo de corrida',
                      'automobilismo de carros antigos', 'automobilismo de carros novos', 'automobilismo de corrida profissional', 'automobilismo de corrida amadora',
                      'automobilismo de competição internacional', 'automobilismo de competição nacional', 'automobilismo de competição regional', 'automobilismo de competição estadual',
                      'automobilismo de competição municipal', 'automobilismo de competição continental', 'automobilismo de competição global', 'automobilismo de competição planetária',
                      'automobilismo de competição lunar', 'automobilismo de competição interestelar', 'automobilismo de competição intergaláctica', 'automobilismo de competição interestelar',
                      'automobilismo de competição interestelar', 'automobilismo de competição galáctica', 'automobilismo de competição interestelar',
                      'automobilismo de competição planetária', 'automobilismo de competição lunar', 'automobilismo de competição interestelar',
                      'automobilismo de competição intergaláctica', 'automobilismo de competição planetária'],

    'jardinagem': ['jardinagem', 'planta', 'flor', 'grama', 'horta', 'jardim', 'árvore', 'fruto', 'paisagismo', 'solo', 'adubo', 'irrigação',
                   'jardinagem caseira', 'jardinagem comunitária', 'jardinagem profissional', 'jardinagem de hortas urbanas', 'jardinagem de hortas rurais',
                   'jardinagem de hortas suburbanas', 'jardinagem de hortas exurbanas', 'jardinagem de hortas submetropolitanas', 'jardinagem de hortas interurbanas',
                   'jardinagem de hortas megarurais', 'jardinagem de hortas megasuburbanas', 'jardinagem de hortas microurbanas', 'jardinagem de hortas microsuburbanas',
                   'jardinagem de hortas semirrurais', 'jardinagem de hortas semirurbanas', 'jardinagem de hortas pararurais', 'jardinagem de hortas paraurbanas',
                   'jardinagem de hortas inrurais', 'jardinagem de hortas inurbanas', 'jardinagem de hortas prorurais', 'jardinagem de hortas prourbanas',
                   'jardinagem de hortas antirurais', 'jardinagem de hortas antiurbanas', 'jardinagem de hortas atrurais', 'jardinagem de hortas atrurbanas',
                   'jardinagem de hortas extrarurais', 'jardinagem de hortas extraurbanas', 'jardinagem de hortas ultrarurais', 'jardinagem de hortas ultrarurbanas',
                   'jardinagem de hortas infrarurais', 'jardinagem de hortas infraurbanas', 'jardinagem de hortas rurais especiais', 'jardinagem de hortas urbanas especiais',
                   'jardinagem de hortas suburbanas especiais', 'jardinagem de hortas exurbanas especiais', 'jardinagem de hortas submetropolitanas especiais',
                   'jardinagem de hortas interurbanas especiais', 'jardinagem de hortas megarurais especiais', 'jardinagem de hortas megasuburbanas especiais',
                   'jardinagem de hortas microurbanas especiais', 'jardinagem de hortas microsuburbanas especiais'],

    'arquitetura': ['arquitetura', 'prédio', 'casa', 'design', 'urbanismo', 'espaço', 'construção', 'projeto', 'plano', 'estrutura', 'fachada', 'interior',
                    'arquitetura moderna', 'arquitetura contemporânea', 'arquitetura clássica', 'arquitetura gótica', 'arquitetura renascentista', 'arquitetura barroca',
                    'arquitetura neoclássica', 'arquitetura românica', 'arquitetura funcionalista', 'arquitetura brutalista', 'arquitetura de interiores', 'arquitetura paisagística',
                    'arquitetura vernacular', 'arquitetura comercial', 'arquitetura residencial', 'arquitetura institucional', 'arquitetura religiosa', 'arquitetura civil',
                    'arquitetura militar', 'arquitetura naval', 'arquitetura ferroviária', 'arquitetura aérea', 'arquitetura terrestre', 'arquitetura extraterrestre', 'arquitetura interna',
                    'arquitetura externa', 'arquitetura intermediária', 'arquitetura de última geração', 'arquitetura de gerações anteriores', 'arquitetura moderna',
                    'arquitetura contemporânea', 'arquitetura clássica', 'arquitetura gótica', 'arquitetura renascentista', 'arquitetura barroca', 'arquitetura neoclássica',
                    'arquitetura românica', 'arquitetura funcionalista', 'arquitetura brutalista', 'arquitetura de interiores', 'arquitetura paisagística'],

    'fotografia': ['fotografia', 'foto', 'imagem', 'câmera', 'lente', 'fotógrafo', 'retrato', 'paisagem', 'exposição', 'enquadramento', 'luz', 'flash',
                   'fotografia analógica', 'fotografia digital', 'fotografia em preto e branco', 'fotografia em cores', 'fotografia de moda', 'fotografia de retrato',
                   'fotografia de paisagem', 'fotografia de natureza', 'fotografia de arquitetura', 'fotografia de rua', 'fotografia documental', 'fotografia de eventos',
                   'fotografia de esportes', 'fotografia subaquática', 'fotografia aérea', 'fotografia macro', 'fotografia de estúdio', 'fotografia experimental',
                   'fotografia de longa exposição', 'fotografia de alta velocidade', 'fotografia infravermelha', 'fotografia panorâmica', 'fotografia digitalizada',
                   'fotografia analógica', 'fotografia digital', 'fotografia em preto e branco', 'fotografia em cores', 'fotografia de moda', 'fotografia de retrato',
                   'fotografia de paisagem', 'fotografia de natureza', 'fotografia de arquitetura', 'fotografia de rua', 'fotografia documental', 'fotografia de eventos',
                   'fotografia de esportes', 'fotografia subaquática', 'fotografia aérea', 'fotografia macro', 'fotografia de estúdio', 'fotografia experimental'],

       'psicologia': ['psicologia', 'mente', 'comportamento', 'emoção', 'terapia', 'psicólogo', 'cérebro', 'transtorno', 'personalidade', 'subconsciente', 'psicanálise',
                   'psicoterapia', 'psicologia clínica', 'psicologia social', 'psicologia do desenvolvimento', 'psicologia cognitiva', 'psicologia educacional',
                   'psicologia organizacional', 'psicologia positiva', 'psicologia experimental', 'psicologia forense', 'psicologia da saúde', 'psicologia do esporte',
                   'psicologia comparada', 'psicologia transpessoal', 'psicologia analítica', 'psicologia humanista', 'psicologia comportamental', 'psicologia evolucionista',
                   'psicologia cultural', 'psicologia da religião', 'psicologia aplicada', 'psicologia ambiental', 'psicologia médica', 'psicologia jurídica', 'psicologia clínica',
                   'psicologia social', 'psicologia do desenvolvimento', 'psicologia cognitiva', 'psicologia educacional', 'psicologia organizacional', 'psicologia positiva',
                   'psicologia experimental', 'psicologia forense', 'psicologia da saúde', 'psicologia do esporte', 'psicologia comparada', 'psicologia transpessoal',
                   'psicologia analítica', 'psicologia humanista', 'psicologia comportamental', 'psicologia evolucionista', 'psicologia cultural'],

    'biologia': ['biologia', 'vida', 'organismo', 'célula', 'genética', 'evolução', 'ecologia', 'biólogo', 'biosfera', 'microbiologia', 'fisiologia', 'botânica',
                 'zoologia', 'anatomia', 'bioquímica', 'ecossistema', 'biodiversidade', 'genoma', 'código genético', 'hereditariedade', 'mutação', 'seleção natural',
                 'adaptabilidade', 'teoria da evolução', 'sustentabilidade', 'biologia molecular', 'biologia celular', 'biologia do desenvolvimento', 'biologia marinha',
                 'biologia terrestre', 'biologia humana', 'biologia vegetal', 'biologia animal', 'biologia evolutiva', 'biologia ambiental', 'biologia de conservação',
                 'biologia sintética', 'biologia teórica', 'biologia aplicada', 'biologia experimental', 'biologia forense', 'biologia médica', 'biologia humana',
                 'biologia vegetal', 'biologia animal', 'biologia evolutiva', 'biologia ambiental', 'biologia de conservação', 'biologia sintética', 'biologia teórica',
                 'biologia aplicada', 'biologia experimental'],

    'química': ['química', 'elemento', 'composto', 'reação', 'átomo', 'molécula', 'químico', 'laboratório', 'fórmula', 'ácido', 'base', 'catalisador',
                'estequiometria', 'termoquímica', 'química orgânica', 'química inorgânica', 'química analítica', 'química física', 'química computacional',
                'química ambiental', 'química industrial', 'química nuclear', 'química farmacêutica', 'química dos materiais', 'química dos polímeros',
                'química dos alimentos', 'química forense', 'química verde', 'química medicinal', 'química bioorgânica', 'química teórica', 'química experimental',
                'química quântica', 'química molecular', 'química dos estados da matéria', 'química dos sólidos', 'química dos líquidos', 'química dos gases',
                'química dos plasmas', 'química dos sólidos', 'química dos líquidos', 'química dos gases', 'química dos plasmas', 'química dos sólidos',
                'química dos líquidos', 'química dos gases', 'química dos plasmas'],

    'física': ['física', 'energia', 'movimento', 'força', 'massa', 'aceleração', 'físico', 'partícula', 'quantum', 'relatividade', 'gravidade', 'inércia',
               'mecânica', 'termodinâmica', 'óptica', 'ondas', 'eletromagnetismo', 'eletricidade', 'magnetismo', 'campo magnético', 'radiação', 'fóton',
               'espectro eletromagnético', 'quantização', 'nuclear', 'fusão nuclear', 'fissão nuclear', 'partícula elementar', 'átomo', 'núcleo atômico',
               'modelo atômico', 'partícula subatômica', 'energia nuclear', 'energia térmica', 'energia mecânica', 'energia elétrica', 'energia magnética',
               'energia cinética', 'energia potencial', 'energia química', 'energia radiante', 'energia solar', 'energia eólica', 'energia hidrelétrica',
               'energia geotérmica', 'energia maremotriz', 'energia de biomassa', 'energia dos oceanos', 'energia limpa', 'energia sustentável'],

    'astronomia': ['astronomia', 'estrela', 'planeta', 'galáxia', 'universo', 'astrônomo', 'telescópio', 'órbita', 'constelação', 'cometa', 'buraco negro', 'cosmos',
                   'exploração espacial', 'sistema solar', 'estrela binária', 'estrela variável', 'estrela anã', 'estrela gigante', 'estrela de nêutrons',
                   'estrela de quarks', 'estrela de buraco negro', 'estrela de matéria escura', 'estrela de energia escura', 'estrela de matéria escura',
                   'estrela de energia escura', 'estrela de escuridão', 'estrela de escuridão e escuridão', 'estrela de escuridão e escuridão',
                   'estrela de escuridão e escuridão', 'estrela de escuridão e escuridão', 'estrela de escuridão e escuridão', 'estrela de escuridão e escuridão',
                   'estrela de escuridão e escuridão', 'estrela de escuridão e escuridão', 'estrela de escuridão e escuridão', 'estrela de escuridão e escuridão',
                   'estrela de escuridão e escuridão', 'estrela de escuridão e escuridão', 'estrela de escuridão e escuridão', 'estrela de escuridão e escuridão',
                   'estrela de escuridão e escuridão', 'estrela de escuridão e escuridão', 'estrela de escuridão e escuridão', 'estrela de escuridão e escuridão',
                   'estrela de escuridão e escuridão', 'estrela de escuridão e escuridão', 'estrela de escuridão e escuridão'],

    'direito': ['direito', 'lei', 'justiça', 'advogado', 'tribunal', 'processo', 'julgamento', 'defesa', 'acusação', 'legislação', 'constituição', 'jurídico',
                'crime', 'criminologia', 'penal', 'civil', 'trabalhista', 'comercial', 'administrativo', 'constitucional', 'tributário', 'ambiental', 'internacional',
                'direitos humanos', 'direitos civis', 'direitos fundamentais', 'sistema jurídico', 'sistema judiciário', 'princípio jurídico', 'interpretação jurídica',
                'jurisprudência', 'precedente', 'código penal', 'código civil', 'contrato', 'responsabilidade civil', 'teoria do direito', 'filosofia do direito',
                'justiça social', 'equidade', 'jurisconsulto', 'advocacia', 'advogado de defesa', 'advogado de acusação', 'defensor público', 'promotor de justiça',
                'juiz', 'magistrado', 'tribunal de justiça', 'tribunal superior', 'advogado criminalista', 'advogado trabalhista', 'advogado empresarial'],

    'matemática': ['matemática', 'número', 'raiz quadrada', 'equação', 'fatoração', 'racional', 'irracional', 'resultado', 'cálculo', 'valor', 'exemplo', 'resolução',
                   'teorema', 'problema', 'geometria', 'álgebra', 'trigonometria', 'estatística', 'probabilidade', 'análise', 'função', 'integral', 'derivada',
                   'teoria dos conjuntos', 'lógica matemática', 'álgebra linear', 'geometria analítica', 'topologia', 'matemática discreta', 'matemática aplicada',
                   'matemática pura', 'matemática computacional', 'matemática financeira', 'matemática recreativa', 'matemática abstrata', 'matemática avançada',
                   'matemática elementar', 'matemática complexa', 'matemática teórica', 'matemática prática', 'matemática experimental', 'matemática empírica',
                   'matemática combinatória', 'matemática aditiva', 'matemática subtrativa', 'matemática multiplicativa', 'matemática divisiva', 'matemática exponencial',
                   'matemática logarítmica', 'matemática semilogarítmica', 'matemática antilogarítmica', 'matemática hipermatemática', 'matemática submatemática']
}
